version: '3'
services:
  nginx:
    container_name: nginx 
    image: nginx
    restart: always
    ports:
      - 80:80
      - 8888:8888
    volumes:
      - /home/docker-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/docker-nginx/log:/var/log/nginx
      - /home/silva/BingDwenDwen:/usr/share/nginx/html